import { Category, ThemeType, LanguageType } from './types';

export const DEFAULT_CATEGORIES: Category[] = [
  { id: '1', name: 'Dry Fruits', icon: '🥜' },
  { id: '2', name: 'Masala', icon: '🌶️' },
  { id: '3', name: 'Spices', icon: '🌿' },
  { id: '4', name: 'Seeds', icon: '🌻' },
  { id: '5', name: 'Pulses', icon: '🫘' },
  { id: '6', name: 'Others', icon: '📦' },
];

export const UNITS = [
  { label: 'Weight', values: ['KG', 'Gram', 'MG', 'Chatak', 'Tola', 'Quintal', 'Ton', 'Pound'] },
  { label: 'Packaging', values: ['Packet', 'Box', 'Bag', 'Pouch', 'Sack', 'Jar', 'Bottle', 'Tin', 'Can', 'Carton', 'Crate'] },
  { label: 'Quantity', values: ['Piece', 'Dozen', 'Bundle', 'Set', 'Pair', 'Unit'] },
];

export const THEMES: { id: ThemeType; name: string; description: string; emoji: string }[] = [
  { id: 'midnight_blue', name: 'Midnight Pro', description: 'Deep contrast, technical precision', emoji: '🌑' },
  { id: 'neo_brutalist', name: 'Neo-Brutalist', description: 'Bold, graphic colors and energy', emoji: '⚡' },
  { id: 'glass_modern', name: 'Glass Morphic', description: 'Immersive frosted glass layers', emoji: '✨' },
  { id: 'luxury_gold', name: 'Luxury Gold', description: 'Premium, elegant gold accents', emoji: '👑' },
  { id: 'premium_dynamic', name: 'Premium Dynamic', description: 'luxurious, smooth animated gradients', emoji: '💎' },
  { id: 'emerald_matrix', name: 'Technical Green', description: 'Matrix data-grid optimization', emoji: '📟' },
];

export const LANGUAGES: { id: LanguageType; name: string; label: string; emoji: string }[] = [
  { id: 'en', name: 'English (US)', label: 'Professional English', emoji: '🇬🇧' },
  { id: 'hi-en', name: 'Hinglish (Mix)', label: 'Hindi + English', emoji: '🇮🇳' },
  { id: 'hi', name: 'हिन्दी (शुद्ध)', label: 'Pure Hindi', emoji: '🇮🇳' },
  { id: 'mr', name: 'मराठी (अस्सल)', label: 'Authentic Marathi', emoji: '🇮🇳' },
];

export const UI_TEXT = {
  en: {
    inventory: 'Unified Inventory',
    search: 'Lookup items, units, or categories...',
    totalItems: 'Node Count',
    totalValue: 'Cumulative Asset Value',
    categories: 'Sector Classification',
    buy: 'Cost Basis',
    wholesale: 'Tier-2 Pricing',
    retail: 'Tier-1 Revenue',
    addItem: 'Initialize New Asset',
    editItem: 'Modify Data Entry',
    save: 'Commit Changes',
    cancel: 'Abort',
    delete: 'Purge Record',
    settings: 'Core Configuration',
    theme: 'UI Visual Deck',
    language: 'Linguistic Interface',
    locked: 'Encrypted',
    unlocked: 'Access Granted',
    enterPin: 'Verification Required',
    createPin: 'Generate Security Key',
    confirmPin: 'Re-verify Key',
    stats: 'Analytics', 
    profile: 'Operator Profile',
    all: 'Global',
    unit: 'Metric',
    quantity: 'Asset Volume',
    buyingPrice: 'Acquisition Cost',
    wholesalePrice: 'Wholesale Vector',
    retailPrice: 'Consumer Retail',
    margin: 'Profit Spread',
    applyMargin: 'Auto-Calibrate',
    notes: 'Internal Log',
    emptyList: 'Registry Empty. System standing by...',
    notesDashboard: 'Notes & Reminders',
    addNote: 'Record New Entry',
    viewAllNotes: 'Expand Log',
    recentPriceChanges: 'Price Volatility Feed',
    login: 'Operator Authorization',
    logout: 'Terminate Session',
    aiInsight: 'AI Business Insight',
    analyze: 'Analyze',
    analyzing: 'Generating...',
    getAiAdvice: 'Get AI-powered pricing strategy & business tips.',
    lastCheck: 'Last Check',
    updateRecord: 'Update record',
    newEntry: 'New entry',
    identityParams: 'Identity parameters',
    financialConfig: 'Financial configuration',
    operationalNotes: 'Operational notes',
    stockStatus: 'Stock Status',
    lowStock: 'Low Stock Alert',
    installApp: 'Deploy Pro Node',
    installDesc: 'Install to home screen for native access',
    deployNode: 'Download & Install Mobile App',
    pwaInstallHint: 'Install it to open like a real mobile app',
    clientShare: 'Client Share',
    broadcast: 'Broadcast via WhatsApp',
    dataEngine: 'Data Engine',
    backupExport: 'Backup & Cloud Export',
    systemCore: 'System Core',
    exportVectors: 'Export Vectors',
    exportExcel: 'Export Data to Excel',
    exportPdf: 'Export Data to PDF',
    backupInfra: 'Backup Infrastructure',
    backupNow: 'Backup System Now',
    restoreBackup: 'Restore Backup',
    maintenanceCore: 'Maintenance Core',
    importData: 'Import External Data',
    clearCache: 'Clear Local Cache',
    systemInfra: 'System Infrastructure',
    metricPrecision: 'Metric Precision',
    typographyDeck: 'Typography Deck',
    error: 'Error',
    success: 'Success',
    deleteConfirm: 'Delete this item?',
    restoreConfirm: 'Restoring will overwrite current data. Proceed?',
    themeDeck: 'UI Visual Deck',
    accentOverlay: 'Brand Accent Overlay',
    securityCloud: 'Security & Cloud',
    securityKey: 'Security Verification Key',
    costProtection: 'Financial cost protection layer',
    cloudSync: 'Cloud Synchronization',
    firebaseSync: 'Auto-sync with Google Firebase',
    autoStealth: 'Automated Stealth',
    stealthDesc: 'Engage masking protocols on start',
    dataLifecycle: 'Data Lifecycle Management',
    authorization: 'Authorization',
    architecture: 'Architecture',
    liveNode: 'Live Operator Instance',
    localSandbox: 'Local Sandbox Environment',
    terminateSession: 'Terminate Session',
    cloudEntry: 'Cloud Entry',
    compare: 'Compare',
    items: 'Items',
    selected: 'Selected',
    sideBySide: 'Side-by-side analysis',
    compareReady: 'Ready for comparison',
    clear: 'Clear',
    lastChanged: 'Last Updated',
    bulkUpdate: 'Bulk Price Update',
    updateSelected: 'Update Selected',
    adjustPrices: 'Adjust prices for multiple items simultaneously.',
    detailedAnalysis: 'Detailed Multi-Item Analysis',
    profitability: 'Profitability',
    revenuePotential: 'Revenue Potential',
    help: 'Help & Knowledge Base',
    onboardingTitle: 'Welcome to Unified Inventory!',
    onboardingSub: 'Let’s set up your store in 30 seconds.',
    tourNext: 'Next Feature',
    tourFinish: 'Start Managing',
    tourSkip: 'Skip Tour',
    step1Title: 'Inventory Dashboard',
    step1Desc: 'Manage your entire stock here. Use search to find items instantly.',
    step2Title: 'Global Search',
    step2Desc: 'Find products by English, Hindi, or Hinglish names.',
    step3Title: 'Analytics & Value',
    step3Desc: 'Track your total asset value and profit margins in real-time.',
    faq1Q: 'How to backup data?',
    faq1A: 'Enable "Cloud Synchronization" in settings to auto-sync with Google Firebase.',
    faq2Q: 'Can I use this offline?',
    faq2A: 'Yes, it works offline as a PWA. Data syncs when you go back online.',
    helpQuickStart: 'Quick Start',
    helpAnalytics: 'Advanced Analytics',
    helpCloud: 'Multi-Device Sync',
    helpSecurity: 'Security & PIN',
    helpTips: 'Expert Tips',
    qs1: 'Add items using the floating + button.',
    qs2: 'Click on any item to edit or view margins.',
    qs3: 'Use the Bottom Nav to switch to Notes or Settings.',
    analyticsDesc: 'Total Value is (Price x Quantity). Margin is the difference between Buy and Retail prices.',
    cloudDesc: 'Sign in with Google to access your data on any device instantly.',
    securityDesc: 'Set a 4-digit PIN to lock sensitive cost prices from customers.',
    loginTitle: 'Unified Inventory',
    loginSubtitle: 'Professional Price & Stock Manager',
    welcomeBack: 'Welcome Back',
    signInToContinue: 'Sign in to access your dashboard',
    emailLabel: 'Email Address',
    passwordLabel: 'Password',
    loginBtn: 'Login',
    googleBtn: 'Sign in with Google',
    otpBtn: 'Login with OTP',
    phoneLabel: 'Mobile Number',
    sendOtp: 'Send OTP',
    verifyOtp: 'Verify OTP',
    forgotPassword: 'Forgot Password?',
    dontHaveAccount: "Don't have an account?",
    signUp: 'Sign Up',
    rememberMe: 'Remember Me',
    loginSuccess: 'Login Successful',
    loginError: 'Login Failed. Please check your credentials.',
    otpSent: 'OTP sent successfully',
    verifying: 'Verifying...',
    authenticating: 'Authenticating...',
  },
  hi: {
    inventory: 'इनवेंटरी मैनेजमेंट',
    search: 'आइटम या श्रेणी ढूंढें...',
    totalItems: 'कुल स्टॉक संख्या',
    totalValue: 'कुल संपत्ति मूल्य',
    categories: 'वर्गीकरण',
    buy: 'लागत मूल्य',
    wholesale: 'थोक दर',
    retail: 'खुदरा दर',
    addItem: 'नया स्टॉक जोड़ें',
    editItem: 'विवरण बदलें',
    save: 'डेटा सुरक्षित करें',
    cancel: 'रद्द करें',
    delete: 'डिलीट करें',
    settings: 'सिस्टम सेटिंग्स',
    theme: 'विजुअल थीम',
    language: 'सञ्चालन भाषा',
    locked: 'सुरक्षित (लॉक)',
    unlocked: 'अनलॉक',
    enterPin: 'पिन दर्ज करें',
    createPin: 'सुरक्षा पिन बनाएं',
    confirmPin: 'पिन की पुष्टि',
    stats: 'डेटा विश्लेषण',
    profile: 'यूजर प्रोफाइल',
    all: 'सभी डेटा',
    unit: 'मात्रक (Unit)',
    quantity: 'कुल मात्रा',
    buyingPrice: 'खरीद कीमत',
    wholesalePrice: 'होलसेल कीमत',
    retailPrice: 'रिटेल कीमत',
    margin: 'मुनाफा',
    applyMargin: 'मार्जिन सेट करें',
    notes: 'विशेष टिपण्णी',
    emptyList: 'कोई डेटा नहीं मिला। सिस्टम तैयार है...',
    notesDashboard: 'व्यवसाय लॉग और अनुस्मारक',
    addNote: 'नया नोट लिखें',
    viewAllNotes: 'सभी लॉग देखें',
    recentPriceChanges: 'मूल्य परिवर्तन इतिहास',
    login: 'सिस्टम लॉगिन',
    logout: 'लॉगआउट',
    aiInsight: 'AI व्यापार सलाह',
    analyze: 'विश्लेषण करें',
    analyzing: 'तैयार हो रहा है...',
    getAiAdvice: 'AI-संचालित मूल्य निर्धारण रणनीति और व्यावसायिक सुझाव प्राप्त करें।',
    lastCheck: 'अंतिम जाँच',
    updateRecord: 'रिकॉर्ड अपडेट करें',
    newEntry: 'नई एंट्री',
    identityParams: 'पहचान पैरामीटर',
    financialConfig: 'वित्तीय कॉन्फ़िगरेशन',
    operationalNotes: 'परिचालन नोट्स',
    stockStatus: 'स्टॉक की स्थिति',
    lowStock: 'कम स्टॉक अलर्ट',
    installApp: 'ऐप इंस्टॉल करें',
    installDesc: 'नेटिव एक्सेस के लिए होम स्क्रीन पर जोड़ें',
    deployNode: 'मोबाइल ऐप डाउनलोड और इंस्टॉल करें',
    pwaInstallHint: 'असली ऐप की तरह चलाने के लिए इंस्टॉल करें',
    clientShare: 'क्लाइंट शेयर',
    broadcast: 'व्हाट्सएप के जरिए भेजें',
    dataEngine: 'डेटा इंजन',
    backupExport: 'बैकअप और क्लाउड एक्सपोर्ट',
    systemCore: 'सिस्टम कोर',
    exportVectors: 'निर्यात (Export)',
    exportExcel: 'एक्सेल में एक्सपोर्ट करें',
    exportPdf: 'PDF में एक्सपोर्ट करें',
    backupInfra: 'बैकअप इंफ्रास्ट्रक्चर',
    backupNow: 'अभी बैकअप लें',
    restoreBackup: 'बैकअप रिस्टोर करें',
    maintenanceCore: 'रखरखाव कोर',
    importData: 'बाहरी डेटा इम्पोर्ट करें',
    clearCache: 'लोकल कैश साफ़ करें',
    systemInfra: 'सिस्टम इंफ्रास्ट्रक्चर',
    metricPrecision: 'परिशुद्धता (Precision)',
    typographyDeck: 'फ़ॉन्ट साइज',
    error: 'त्रुटि',
    success: 'सफलता',
    deleteConfirm: 'क्या आप इसे हटाना चाहते हैं?',
    restoreConfirm: 'रिस्टोर करने से वर्तमान डेटा बदल जाएगा। क्या आप जारी रखना चाहते हैं?',
    themeDeck: 'विजुअल डेक',
    accentOverlay: 'ब्रांड एक्सेंट ओवरले',
    securityCloud: 'सुरक्षा और क्लाउड',
    securityKey: 'सुरक्षा वेरिफिकेशन पिन',
    costProtection: 'वित्तीय सुरक्षा परत',
    cloudSync: 'क्लाउड सिंक्रोनाइज़ेशन',
    firebaseSync: 'गूगल फायरबेस के साथ सिंक',
    autoStealth: 'स्वचालित गोपनीयता (Stealth)',
    stealthDesc: 'शुरुआत में लागत छुपाएं',
    dataLifecycle: 'डेटा जीवनचक्र प्रबंधन',
    authorization: 'प्राधिकरण',
    architecture: 'आर्किटेक्चर',
    liveNode: 'लाइव ऑपरेटर इंस्टेंस',
    localSandbox: 'लोकल सैंडबॉक्स वातावरण',
    terminateSession: 'सत्र समाप्त करें',
    cloudEntry: 'क्लाउड एंट्री',
    compare: 'तुलना करें',
    items: 'आइटम',
    selected: 'चुने गए',
    sideBySide: 'एक साथ तुलना',
    compareReady: 'तुलना के लिए तैयार',
    clear: 'साफ करें',
    lastChanged: 'अंतिम अपडेट',
    bulkUpdate: 'थोक मूल्य अपडेट',
    updateSelected: 'चुने हुए अपडेट करें',
    adjustPrices: 'एक साथ कई वस्तुओं की कीमतें बदलें।',
    detailedAnalysis: 'विस्तृत तुलना विश्लेषण',
    profitability: 'लाभदायकता',
    revenuePotential: 'संभावित राजस्व',
    help: 'मदद और जानकारी',
    onboardingTitle: 'आपका स्वागत है!',
    onboardingSub: 'चलिए 30 सेकंड में सेटअप करते हैं।',
    tourNext: 'अगला',
    tourFinish: 'शुरू करें',
    tourSkip: 'छोड़ें',
    step1Title: 'स्टॉक डैशबोर्ड',
    step1Desc: 'अपना सारा स्टॉक यहाँ मैनेज करें।',
    step2Title: 'सर्च',
    step2Desc: 'किसी भी भाषा में सामान ढूंढें।',
    step3Title: 'एनालिटिक्स',
    step3Desc: 'अपना कुल मुनाफा और वैल्यू यहाँ देखें।',
    faq1Q: 'डेटा बैकअप कैसे करें?',
    faq1A: 'सेटिंग्स में "क्लाउड सिंक्रोनाइज़ेशन" चालू करें।',
    faq2Q: 'क्या ऑफलाइन इस्तेमाल कर सकते हैं?',
    faq2A: 'हाँ, यह PWA की तरह ऑफलाइन भी काम करता है।',
    helpQuickStart: 'क्विक स्टार्ट',
    helpAnalytics: 'एडवांस्ड एनालिटिक्स',
    helpCloud: 'मल्टी-डिवाइस सिंक',
    helpSecurity: 'सुरक्षा और पिन',
    helpTips: 'एक्सपर्ट टिप्स',
    qs1: 'फ्लोटिंग + बटन से आइटम जोड़ें।',
    qs2: 'मार्जिन देखने के लिए किसी भी आइटम पर क्लिक करें।',
    qs3: 'नोट्स या सेटिंग्स पर जाने के लिए बॉटम नेविगेशन का उपयोग करें।',
    analyticsDesc: 'कुल मूल्य (कीमत x मात्रा) है। मार्जिन खरीद और खुदरा कीमतों के बीच का अंतर है।',
    cloudDesc: 'किसी भी डिवाइस पर अपना डेटा तुरंत एक्सेस करने के लिए Google से साइन इन करें।',
    securityDesc: 'ग्राहकों से संवेदनशील लागत कीमतों को सुरक्षित रखने के लिए 4-अंकीय पिन सेट करें।',
  },
  mr: {
    inventory: 'मालमत्ता व्यवस्थापन',
    search: 'वस्तू किंवा श्रेणी शोधा...',
    totalItems: 'एकूण संख्या',
    totalValue: 'एकूण मालमत्ता मूल्य',
    categories: 'वर्गवारी',
    buy: 'मूळ किंमत',
    wholesale: 'घाऊक दर',
    retail: 'किरकोळ दर',
    addItem: 'नवीन नोंद करा',
    editItem: 'नोंद सुधारित करा',
    save: 'बदल जतन करा',
    cancel: 'रद्द करा',
    delete: 'कायमचे हटवा',
    settings: 'मुख्य सेटिंग्ज',
    theme: 'दृश्य स्वरूप',
    language: 'संवाद भाषा',
    locked: 'सुरक्षित',
    unlocked: 'प्रवेश खुला',
    enterPin: 'पिन टाका',
    createPin: 'सुरक्षा पिन तयार करा',
    confirmPin: 'पिनची पडताळणी',
    stats: 'आकडेवारी',
    profile: 'वापरकर्ता प्रोफाइल',
    all: 'सर्व नोंदी',
    unit: 'परिमाण (Unit)',
    quantity: 'एकूण प्रमाण',
    buyingPrice: 'खरेदी दर',
    wholesalePrice: 'घाऊक दर',
    retailPrice: 'रिटेल दर',
    margin: 'नफा',
    applyMargin: 'मार्जिन लावा',
    notes: 'महत्त्वाची नोंद',
    emptyList: 'काहीही आढळले नाही. सिस्टीम सज्ज आहे...',
    notesDashboard: 'व्यवसाय टीपा आणि आठवण',
    addNote: 'नवीन टीप जोडा',
    viewAllNotes: 'सर्व पहा',
    recentPriceChanges: 'दर बदल फीड',
    login: 'प्रवेश करा',
    logout: 'बाहेर पडा',
    aiInsight: 'AI व्यावसायिक सल्ला',
    analyze: 'विश्लेषण करा',
    analyzing: 'तयार होत आहे...',
    getAiAdvice: 'AI-आधारित किंमत धोरण आणि व्यवसाय टिपा मिळवा.',
    lastCheck: 'शेवटची तपासणी',
    updateRecord: 'नोंद अपडेट करा',
    newEntry: 'नवीन एन्ट्री',
    identityParams: 'ओळख पॅरामीटर्स',
    financialConfig: 'आर्थिक कॉन्फिगरेशन',
    operationalNotes: 'ऑपरेशनल नोट्स',
    stockStatus: 'स्टॉक स्थिती',
    lowStock: 'कमी स्टॉक अलर्ट',
    installApp: 'अ‍ॅप इंस्टॉल करा',
    installDesc: 'वापरासाठी होम स्क्रीनवर जोडा',
    deployNode: 'मोबाईल ॲप डाउनलोड आणि इंस्टॉल करा',
    pwaInstallHint: 'खऱ्या ॲपप्रमाणे वापरण्यासाठी इन्स्टॉल करा',
    clientShare: 'क्लाइंट शेअर',
    broadcast: 'व्हॉट्सअ‍ॅपद्वारे शेअर करा',
    dataEngine: 'डेटा इंजिन',
    backupExport: 'बॅकअप आणि क्लाउड एक्सपोर्ट',
    systemCore: 'सिस्टम कोअर',
    exportVectors: 'डेटा एक्सपोर्ट',
    exportExcel: 'एक्सेलमध्ये एक्सपोर्ट करा',
    exportPdf: 'PDF मध्ये एक्सपोर्ट करा',
    backupInfra: 'बॅकअप इन्फ्रास्ट्रक्चर',
    backupNow: 'आताच बॅकअप घ्या',
    restoreBackup: 'बॅकअप रिस्टोर करा',
    maintenanceCore: 'मेंटेन्स कोअर',
    importData: 'बाह्य डेटा इम्पोर्ट करा',
    clearCache: 'लोकल कॅश साफ करा',
    systemInfra: 'सिस्टम इन्फ्रास्ट्रक्चर',
    metricPrecision: 'अचूकता (Precision)',
    typographyDeck: 'फॉन्ट आकार',
    error: 'त्रुटि',
    success: 'यश',
    deleteConfirm: 'तुम्ही हे हटवू इच्छिता का?',
    restoreConfirm: 'रिस्टोर केल्याने सध्याचा डेटा बदलला जाईल. पुढे जायचे का?',
    themeDeck: 'विजुअल डेक',
    accentOverlay: 'ब्रँड अ‍ॅक्सेंट ओव्हरले',
    securityCloud: 'सुरक्षा आणि क्लाउड',
    securityKey: 'सुरक्षा पडताळणी पिन',
    costProtection: 'आर्थिक सुरक्षा स्तर',
    cloudSync: 'क्लाउड सिंक्रोनाइझेशन',
    firebaseSync: 'गूगल फायरबेससह सिंक',
    autoStealth: 'स्वयंचलित गोपनीयता',
    stealthDesc: 'सुरुवातीला खरेदी दर लपवा',
    dataLifecycle: 'डेटा लाइफसायकल मॅनेजमेंट',
    authorization: 'प्राधिकरण',
    architecture: 'आर्किटेक्चर',
    liveNode: 'लाईव्ह ऑपरेटर इन्स्टन्स',
    localSandbox: 'लोकल सँडबॉक्स वातावरण',
    terminateSession: 'सत्र समाप्त करा',
    cloudEntry: 'क्लाउड एन्ट्री',
    compare: 'तुलना करा',
    items: 'वस्तू (Items)',
    selected: 'निवडलेले',
    sideBySide: 'तुलनात्मक विश्लेषण',
    compareReady: 'तुलना करण्यासाठी तयार',
    clear: 'साफ करा',
    lastChanged: 'शेवटचे अपडेट',
    bulkUpdate: 'मोठ्या प्रमाणात दर अपडेट',
    updateSelected: 'निवडलेले अपडेट करा',
    adjustPrices: 'एकाच वेळी अनेक वस्तूंचे दर बदला.',
    detailedAnalysis: 'तपशीलवार विश्लेषण',
    profitability: 'नफा क्षमता',
    revenuePotential: 'संभावित महसूल',
    help: 'मदत आणि माहिती',
    onboardingTitle: 'तुमचे स्वागत आहे!',
    onboardingSub: 'चला ३० सेकंदात सेटअप करूया.',
    tourNext: 'पुढील',
    tourFinish: 'सुरू करा',
    tourSkip: 'वगळा',
    step1Title: 'स्टॉक डॅशबोर्ड',
    step1Desc: 'तुमचा सर्व स्टॉक येथे व्यवस्थापित करा.',
    step2Title: 'शोध',
    step2Desc: 'कोणत्याही भाषेत वस्तू शोधा.',
    step3Title: 'अ‍ॅनालिटिक्स',
    step3Desc: 'तुमचा एकूण नफा आणि मूल्य येथे पहा.',
    faq1Q: 'डेटा बॅकअप कसा घ्यावा?',
    faq1A: 'सेटिंग्जमध्ये "क्लाउड सिंक्रोनाइझेशन" सक्षम करा.',
    faq2Q: 'मी हे ऑफलाइन वापरू शकतो का?',
    faq2A: 'हो, हे PWA म्हणून ऑफलाइन काम करते.',
    helpQuickStart: 'क्विक स्टार्ट',
    helpAnalytics: 'प्रगत विश्लेषण',
    helpCloud: 'मल्टी-डिव्हाइस सिंक',
    helpSecurity: 'सुरक्षा आणि पिन',
    helpTips: 'तज्ञांच्या टिप्स',
    qs1: 'फ्लोटिंग + बटण वापरून वस्तू जोडा.',
    qs2: 'मार्जिन पाहण्यासाठी कोणत्याही वस्तूवर क्लिक करा.',
    qs3: 'नोट्स किंवा सेटिंग्सवर जाण्यासाठी बॉटम नेव्हिगेशन वापरा.',
    analyticsDesc: 'एकूण मूल्य (किंमत x प्रमाण) आहे. मार्जिन खरेदी आणि किरकोळ किमतींमधील फरक आहे.',
    cloudDesc: 'कोणत्याही डिव्हाइसवर तुमचा डेटा त्वरित प्रवेश करण्यासाठी Google सह साइन इन करा.',
    securityDesc: 'ग्राहकांपासून संवेदनशील किमती सुरक्षित ठेवण्यासाठी ४-अंकी पिन सेट करा.',
  },
  'hi-en': {
    inventory: 'Inventory Dashboard',
    search: 'Search kijiye...',
    totalItems: 'Total Stock',
    totalValue: 'Net Asset Value',
    categories: 'Categories',
    buy: 'Cost Price',
    wholesale: 'Wholesale Price',
    retail: 'Retail Price',
    addItem: 'Naya Item add karein',
    editItem: 'Details update karein',
    save: 'Data Save karein',
    cancel: 'Cancel',
    delete: 'Record Delete karein',
    settings: 'Controls',
    theme: 'App Look',
    language: 'Language Selection',
    locked: 'Locked State',
    unlocked: 'Unlocked',
    enterPin: 'Pin mang raha hai',
    createPin: 'New Pin set karein',
    confirmPin: 'Dobara Pin dalein',
    stats: 'Stats Deck',
    profile: 'User Profile',
    all: 'Full List',
    unit: 'Unit Metric',
    quantity: 'Quantity Status',
    buyingPrice: 'Buying Cost',
    wholesalePrice: 'Wholesale Price',
    retailPrice: 'Retail Price',
    margin: 'Margin Gap',
    applyMargin: 'Auto Margins',
    notes: 'Extra Info',
    emptyList: 'Kuch nahi mila. Ready to add...',
    notesDashboard: 'Business Notes & Reminders',
    addNote: 'Entry Add Karein',
    viewAllNotes: 'Show Everything',
    recentPriceChanges: 'Price History Tracker',
    login: 'Log-In Karein',
    logout: 'Session End',
    aiInsight: 'AI Business Insight',
    analyze: 'Analyze',
    analyzing: 'Calculating...',
    getAiAdvice: 'AI pricing strategy aur business tips ke liye scan karein.',
    lastCheck: 'Last Check',
    updateRecord: 'Update record',
    newEntry: 'New entry',
    identityParams: 'Identify parameters',
    financialConfig: 'Finance settings',
    operationalNotes: 'Notes section',
    stockStatus: 'Stock status',
    lowStock: 'Kam stock ki alert',
    installApp: 'App install karein',
    installDesc: 'Home screen par add karein direct access ke liye',
    deployNode: 'Mobile App Download & Install Karein',
    pwaInstallHint: 'Asli app ki tarah upyog karne ke liye install karein',
    clientShare: 'Share with Client',
    broadcast: 'WhatsApp par bhejein',
    dataEngine: 'Data Center',
    backupExport: 'Backup aur Cloud',
    systemCore: 'System Settings',
    exportVectors: 'Export karein',
    exportExcel: 'Excel sheet banayein',
    exportPdf: 'PDF banayein',
    backupInfra: 'Backup Systems',
    backupNow: 'Backup lein',
    restoreBackup: 'Purana data layein',
    maintenanceCore: 'Clean up',
    importData: 'Naya data layein',
    clearCache: 'Cache saaf karein',
    systemInfra: 'Internal logic',
    metricPrecision: 'Calculation precision',
    typographyDeck: 'Font Size adjust karein',
    error: 'Kuch galat hua',
    success: 'Done!',
    deleteConfirm: 'Delete karna hai?',
    restoreConfirm: 'Purana data replace ho jayega. Sure?',
    themeDeck: 'Visual Look',
    accentOverlay: 'Brand Colors',
    securityCloud: 'Security & Backup',
    securityKey: 'Security PIN',
    costProtection: 'Money safety layer',
    cloudSync: 'Cloud Syncing',
    firebaseSync: 'Firebase auto-sync',
    autoStealth: 'Stealth Mode on startup',
    stealthDesc: 'Cost prices hide karein',
    dataLifecycle: 'Data Management',
    authorization: 'Authorization',
    architecture: 'Architecture',
    liveNode: 'Live Instance',
    localSandbox: 'Local Environment',
    terminateSession: 'Session End',
    cloudEntry: 'Cloud Entry',
    compare: 'Compare',
    items: 'Items',
    selected: 'Selected',
    sideBySide: 'Compare items',
    compareReady: 'Compare click karo',
    clear: 'Hatao',
    lastChanged: 'Update hua',
    bulkUpdate: 'Bulk Price Update',
    updateSelected: 'Selected Update Karein',
    adjustPrices: 'Kayi items ke rates ek saath change karein.',
    detailedAnalysis: 'Detailed Analysis',
    profitability: 'Profit Percentage',
    revenuePotential: 'Total Revenue',
    help: 'Help aur Guide',
    onboardingTitle: 'Unified Inventory mein Swagat hai!',
    onboardingSub: 'Chaliye 30 seconds mein setup karte hain.',
    tourNext: 'Agla Feature',
    tourFinish: 'Shuru karien',
    tourSkip: 'Chhod dein',
    step1Title: 'Inventory Dashboard',
    step1Desc: 'Apna pura stock yahan manage karein.',
    step2Title: 'Easy Search',
    step2Desc: 'English, Hindi ya Hinglish mein items dhundhein.',
    step3Title: 'Analytics',
    step3Desc: 'Total value aur profit margins live dekhein.',
    faq1Q: 'Backup kaise karein?',
    faq1A: 'Settings mein "Cloud Synchronization" on karein sync ke liye.',
    faq2Q: 'Offline use kar sakte hain?',
    faq2A: 'Haan, PWA mode mein offline bhi kaam karega.',
    helpQuickStart: 'Quick Start',
    helpAnalytics: 'Advanced Analytics',
    helpCloud: 'Cloud Sync',
    helpSecurity: 'Security & PIN',
    helpTips: 'Pro Tips',
    qs1: 'Floating + button se items add karein.',
    qs2: 'Kisi bhi item par click karke details edit karein.',
    qs3: 'Bottom nav se Notes ya Settings switch karein.',
    analyticsDesc: 'Total Value = (Price x Quantity). Margin buy aur retail price ka difference hai.',
    cloudDesc: 'Google login karein taaki data sabhi devices par sync ho jaye.',
    securityDesc: 'Customer se rates chhupane ke liye 4-digit PIN set karein.',
  },
};
